# media-gfx/gimp: plain O2 + SELECT_MASK define.
COMMON_FLAGS="-O2 -pipe -march=native -DSELECT_MASK=fd_set ${LIB_FLAGS} ${UARG_FLAGS}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
CPPFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS}"
