COMMON_FLAGS="-march=native -O2 -pipe -D_DEFAULT_SOURCE -stdlib=libc++"
CFLAGS="-march=native -O2 -pipe -D_DEFAULT_SOURCE -stdlib=libc++"
CXXFLAGS="-march=native -O2 -pipe -D_DEFAULT_SOURCE -stdlib=libc++"
LDFLAGS="-Wl,--as-needed"