# clang but against GCC's libstdc++ with explicit gcc-15 header/lib paths;
# ccache off. For packages that hard-require libstdc++ internals
# (ragel, colm, Tensile).
FEATURES="-ccache sandbox usersandbox multilib-strict fixlafiles unmerge-orphans noman nodoc noinfo notitles parallel-install parallel-fetch clean-logs network-sandbox"
COMMON_FLAGS="${CLEAN_FLAGS} -lstdc++ -lm -lc++ -lc++abi -lgcc_s -lunwind -lc++ -unwindlib=libunwind  --gcc-install-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/15 -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/15/include/g++-v15 -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/15/include/g++-v15/x86_64-pc-linux-gnu"
CMAKE_EXTRA_VARIABLES="-DCMAKE_HIP_FLAGS=-isystem /usr/lib/gcc/x86_64-pc-linux-gnu/15/include/g++-v15 -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/15/include/g++-v15/x86_64-pc-linux-gnu"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS}"
