# Default flags minus Polly/alignment. First fallback for packages that
# miscompile, ICE, or crash under Polly.
COMMON_FLAGS="${OPT_FLAGS} ${VTABLE_OPT_FLAGS} ${LTO_FLAGS} ${LTO_UNI_FLAGS} ${LIB_FLAGS} ${UARG_FLAGS} ${GCCLIB_FLAGS}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS} ${LD_CLEAN_FLAGS}"
