############################################################################
# Remove sample-PGO/profile mapping metadata.
#
# Use when sampled-profile mapping support breaks a package.
############################################################################

COMMON_FLAGS="${POLLY_FLAGS} ${AGGRO_OPT_FLAGS} ${BOLT_READY_FLAGS} ${SECTION_FLAGS} ${VISIBILITY_FLAGS} ${OPT_REMARK_FLAGS} ${VTABLE_OPT_FLAGS} ${LTO_FLAGS} ${LTO_UNI_FLAGS} ${UARG_FLAGS}"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS} ${CXX_VISIBILITY_FLAGS} ${LIB_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

LDFLAGS="${LDFLAGS} ${COMMON_FLAGS} ${LD_CLEAN_FLAGS}"
