# O3.conf but without the vtable/whole-program LTO extras (keeps
# -funified-lto only). xorg-server lives here.
COMMON_FLAGS="${O3_BASE_FLAGS} ${LTO_FLAGS} -funified-lto ${LIB_FLAGS} ${UARG_FLAGS} ${GCCLIB_FLAGS}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS} ${LD_CLEAN_FLAGS}"
