############################################################################
# Rust demotion: remove panic-abort behavior.
#
# Use for Rust packages/crates that require unwinding behavior.
############################################################################

RUSTFLAGS="-C embed-bitcode=yes -C lto=thin -C codegen-units=1 -C target-cpu=native -C opt-level=3 -Clinker=clang -Clinker-plugin-lto -Clink-arg=-fuse-ld=lld -Clink-arg=-funified-lto -Clink-arg=-Wl,--gc-sections -Clink-arg=-Wl,--icf=safe"
