# Disable ccache plus sandboxes that conflict with these builds.
# Use only when sandboxing itself is known to break the package build.
FEATURES="-ccache -sandbox -usersandbox multilib-strict fixlafiles unmerge-orphans noman nodoc noinfo notitles parallel-install parallel-fetch clean-logs -network-sandbox"
