pre_src_compile() {
    if [[ ${CATEGORY}/${PN} == "dev-tcltk/blt" ]]; then
        sed -i \
            's/Mark(cubePtr, color\.value, lut)/Mark(cubePtr, color.value, (unsigned int (*)[33][33])lut)/' \
            "${S}/generic/bltImage.c"
        sed -i \
            's/MapColors(src, dest, lut);/MapColors(src, dest, (unsigned int (*)[33][33])lut);/' \
            "${S}/generic/bltImage.c"
    fi
}
