#!/usr/bin/env python3
import argparse,json,hashlib,collections
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--states',required=True);ap.add_argument('--backends',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();s=json.load(open(a.states));b={x['cpv']:x for x in json.load(open(a.backends))['packages']}; rows=[]
 overrides={'sys-devel/gcc-17.0.9999':('pgo-gcc','gcc-native-toolchain'),'net-libs/libmnl-1.0.5':('pgo-clang-ir','native-library-ebuild'),'sys-apps/iucode_tool-2.3.1-r2':('pgo-clang-ir','native-utility-ebuild'),'sys-process/time-1.10':('pgo-clang-ir','native-utility-ebuild'),'app-portage/cpuid2cpuflags-18':('pgo-clang-ir','native-utility-ebuild'),'dev-libs/tree-sitter-bash-0.25.1':('pgo-clang-ir','generated-native-parser'),'dev-util/clinfo-9999':('pgo-clang-ir','native-utility-ebuild'),'dev-build/xfce4-dev-tools-4.20.0':('unsupported-by-upstream-toolchain','tooling-only-no-profiled-workload'),'app-autodesk/adp-desktop-sdk-6.3.34':('unsupported-by-upstream-toolchain','prebuilt-vendor-sdk'),'app-autodesk/adsk-identity-manager-1.18.1.2-r1':('unsupported-by-upstream-toolchain','prebuilt-vendor-binary'),'app-autodesk/adsk-licensing-16.0.3.14414':('unsupported-by-upstream-toolchain','prebuilt-vendor-binary'),'app-editors/sublime-text-4_p4200':('unsupported-by-upstream-toolchain','prebuilt-binary'),'app-office/onlyoffice-bin-9.4.0':('unsupported-by-upstream-toolchain','prebuilt-binary'),'dev-util/shellcheck-bin-0.11.0':('unsupported-by-upstream-toolchain','prebuilt-binary'),'media-gfx/bifrost-3.1.0.8':('unsupported-by-upstream-toolchain','prebuilt-vendor-binary'),'media-gfx/lookdevx-2.2.0':('unsupported-by-upstream-toolchain','prebuilt-vendor-binary'),'media-gfx/maya-2027.2-r1':('unsupported-by-upstream-toolchain','prebuilt-vendor-binary'),'media-gfx/maya-usd-0.37.0':('unsupported-by-upstream-toolchain','prebuilt-vendor-binary'),'media-gfx/substance-maya-3.0.6':('unsupported-by-upstream-toolchain','prebuilt-vendor-binary'),'media-sound/spotify-1.2.96':('unsupported-by-upstream-toolchain','prebuilt-binary'),'www-client/firefox-bin-152.0.5':('unsupported-by-upstream-toolchain','prebuilt-binary')}
 for x in s['records']:
  cpv=x['cpv']; ev=sorted(set(b[cpv]['backend_evidence']+b[cpv]['inherits'])); phases=b[cpv]['phase_functions']
  if cpv in overrides: lane,reason=overrides[cpv]
  elif x['state']!='pending-pgo-classification': lane=x['state']; reason=x['reason_code']
  elif any('cargo' in z or z in ('rust','rust-toolchain') for z in ev): lane='pgo-rust';reason='cargo-or-rust-eclass'
  elif any('go' in z for z in ev): lane='pgo-go';reason='go-eclass'
  elif any(any(k in z for k in ('cmake','meson','autotools','llvm','toolchain-funcs','libtool','ecm','frameworks.kde.org','xorg-3','multilib','qt6-build','gstreamer')) for z in ev) or any(z in phases for z in ('src_compile','src_configure')): lane='pgo-clang-ir';reason='native-compiled-eclass-or-phase'
  elif any('python' in z or 'java' in z or z in ('distutils-r1','pypi','ruby-fakegem','perl-module') for z in ev): lane='unsupported-by-upstream-toolchain';reason='managed-language-or-runtime-eclass'
  else: lane='pending-pgo-classification';reason='no-supported-backend-evidence'
  rows.append({'cpv':cpv,'lane':lane,'reason_code':reason,'backend_evidence':ev})
 out={'record_type':'pgo-lane-candidates','schema_version':1,'source_state':s['sha256'],'packages':rows};out['counts']=dict(collections.Counter(x['lane'] for x in rows));out['sha256']=hashlib.sha256(json.dumps(out,sort_keys=True,separators=(',',':')).encode()).hexdigest();json.dump(out,open(a.output,'w'),sort_keys=True,indent=2);open(a.output,'a').write('\n');print(out['counts'])
if __name__=='__main__':main()
